# - name: reboot
#   command: shutdown -r +0 'Ansible Reboot triggered  && sleep 1'
#   async: 0
#   poll: 0
#   ignore_errors: true
#   become: true

# - name: wait for reboot to finish
#   local_action: wait_for host={{ ansible_host }} state=started port=22 delay=50 timeout=120
#   become: false

- debug:
        msg: "Will reboot and then wait for {{ ansible_ssh_host }}:{{ ansible_ssh_port }} to come back to life"

- name: reboot
  shell: sleep 2 && shutdown -r now "Ansible triggered reboot"
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for system to boot up
  local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }} state=started delay=15 timeout=100
  become: False

- debug:
  msg: "We're back again. Running on {{ inventory_hostname }}"
