# ansible-playbook -i ~/ansible/hosts /playbooks/new-default.yml
---
- hosts: berry
  gather_facts: yes
  vars:
    wifi_country: "DE"
    locale: "en_US.UTF-8"
    keyboard: "pc104"
    keyboard_layout: "us"
    timezone: Europe/Berlin
    locale_options:
      # Disable Default (GB) Locale
      - regexp: "^#?en_GB.UTF-8 UTF-8"
        line: "# en_GB.UTF-8 UTF-8"
      # Enable US Locale
      - regexp: "^#?en_US.UTF-8 UTF-8"
        line: "en_US.UTF-8 UTF-8"

  pre_tasks:
  - name: "Load env vars"
    tags: always
    set_fact:
      hostname: '{{ lookup("env", "PI_HOSTNAME") }}'
      wifi_ssid: '{{ lookup("env", "PI_WIFI_SSID") }}'
      wifi_password: '{{ lookup("env", "PI_WIFI_PASSWORD") }}'
      ssh_key: '{{ lookup("env", "PI_SSH") }}'
      root_pw: '{{ lookup("env", "PI_PASS") }}'

  tasks:
    # Change root pw
    - name: Change Password
      user:
        name: pi
        password: "{{ root_pw }}"
        update_password: always
      become: yes

    # Expand the filesystem
    - include: ../tasks/expand-filesystem.yml
      tags: setup

    # Set Internationalization Options
    - include: ../tasks/internationalization.yml
      tags: setup

    # Set WiFi Options
    - include: ../tasks/wifi.yml
      tags: setup

    - name: Create SSH folder
      file: path=~/.ssh state=directory

    - name: Set up SSH Key from a template
      template: src=../templates/authorized_keys dest=~/.ssh/authorized_keys

    - name: run 'dpkg --configure -a'
      become: yes
      command: dpkg --configure -a

    # Run apt-get update and apt-get upgrade
    - include: ../tasks/update.yml
      tags: update

    # Set the hostname
    - include: ../tasks/hostname.yml
      tags: setup

  handlers:

    - include: ../handlers/reboot.yml
      tags: system

    - include: ../handlers/tzdata.yml
      tags: system

